name: Build and Deplot to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2 

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: darkxprime/user-app:latest

      - name: Verfiy Pushed Image
        run: docker pull darkxprime/user-app:latest 

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull darkxprime/user-app:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d --name web-app -p 3000:3000 -e DATABASE_URL="${{ secrets.DB_URL}}" darkxprime/user-app:latest